# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image to build the project
FROM node:18-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the project files
COPY . .

# Build the project
RUN npm run build

# Use a lighter Node.js image for the production stage
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the built files and node_modules from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Set the entry point to start the server
ENTRYPOINT ["node", "build/index.js"]
